In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# coffee data
url="https://storage.googleapis.com/second-try-ml/air-pollution/Test.csv"
data=pd.read_csv(url)

In [8]:
data.head(15)

,Place_ID X Date,Date,Place_ID,precipitable_water_entire_atmosphere,relative_humidity_2m_above_ground,specific_humidity_2m_above_ground,temperature_2m_above_ground,u_component_of_wind_10m_above_ground,v_component_of_wind_10m_above_ground,L3_NO2_NO2_column_number_density,...,L3_SO2_sensor_zenith_angle,L3_SO2_solar_azimuth_angle,L3_SO2_solar_zenith_angle,L3_CH4_CH4_column_volume_mixing_ratio_dry_air,L3_CH4_aerosol_height,L3_CH4_aerosol_optical_depth,L3_CH4_sensor_azimuth_angle,L3_CH4_sensor_zenith_angle,L3_CH4_solar_azimuth_angle,L3_CH4_solar_zenith_angle
0,0OS9LVX X 2020-01-02,2020-01-02,0OS9LVX,11.600000,30.200001,0.004090,14.656824,3.956377,0.712605,0.000053,...,1.445658,-95.984984,22.942019,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0OS9LVX X 2020-01-03,2020-01-03,0OS9LVX,18.300001,42.900002,0.005950,15.026544,4.230430,0.661892,0.000050,...,34.641758,-95.014908,18.539116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0OS9LVX X 2020-01-04,2020-01-04,0OS9LVX,17.600000,41.299999,0.005900,15.511041,5.245728,1.640559,0.000050,...,55.872276,-94.015418,14.140820,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0OS9LVX X 2020-01-05,2020-01-05,0OS9LVX,15.011948,53.100002,0.007090,14.441858,5.454001,-0.190532,0.000055,...,59.174188,-97.247602,32.730553,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0OS9LVX X 2020-01-06,2020-01-06,0OS9LVX,9.700000,71.599998,0.008080,11.896295,3.511787,-0.279441,0.000055,...,40.925873,-96.057265,28.320527,1831.261597,3229.118652,0.031068,-100.278343,41.847080,-95.910744,28.498789
5,0OS9LVX X 2020-01-07,2020-01-07,0OS9LVX,13.400001,69.300003,0.008282,12.744867,3.945603,-0.240925,0.000058,...,10.836973,-94.799643,23.907860,1837.774723,2994.670721,0.021529,-97.429578,11.777910,-94.482957,24.036353
6,0OS9LVX X 2020-01-08,2020-01-08,0OS9LVX,7.100000,32.500000,0.004213,14.008264,4.931650,-0.121121,0.000057,...,24.739306,-93.415295,19.504812,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0OS9LVX X 2020-01-09,2020-01-09,0OS9LVX,9.500000,38.299999,0.005008,14.126581,4.487686,2.149639,0.000064,...,49.978513,-91.778515,15.111800,1844.618479,3514.182445,0.119388,73.839111,49.383339,-91.714035,15.281165
8,0OS9LVX X 2020-01-10,2020-01-10,0OS9LVX,8.400001,40.000000,0.005370,14.492181,3.642092,1.463457,0.000060,...,64.243082,-92.910995,22.243903,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0OS9LVX X 2020-01-11,2020-01-11,0OS9LVX,10.396144,29.700001,0.004113,14.959802,1.508940,1.440989,0.000053,...,48.141814,-94.863053,29.366920,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,0OS9LVX X 2020-01-12,2020-01-12,0OS9LVX,10.700000,26.300001,0.004200,17.127954,3.980806,1.612266,0.000066,...,22.301008,-93.300754,24.960765,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0OS9LVX X 2020-01-13,2020-01-13,0OS9LVX,8.700000,24.600000,0.003645,16.021326,1.868848,0.364045,0.000061,...,13.452336,-91.491864,20.563057,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,0OS9LVX X 2020-01-14,2020-01-14,0OS9LVX,10.500000,32.200001,0.004674,15.683954,2.942925,1.950105,0.000057,...,42.946515,-89.214180,16.181873,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,0OS9LVX X 2020-01-15,2020-01-15,0OS9LVX,10.500000,18.600000,0.002599,15.062128,2.302515,0.209780,0.000061,...,60.792176,-85.907948,11.814185,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,0OS9LVX X 2020-01-16,2020-01-16,0OS9LVX,11.300000,14.900001,0.002185,15.802789,3.184690,-0.559006,0.000056,...,54.167110,-93.433832,30.515105,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [15]:
column_names = [data.columns]
print(column_names)

[Index(['Place_ID X Date', 'Date', 'Place_ID',
       'precipitable_water_entire_atmosphere',
       'relative_humidity_2m_above_ground',
       'specific_humidity_2m_above_ground', 'temperature_2m_above_ground',
       'u_component_of_wind_10m_above_ground',
       'v_component_of_wind_10m_above_ground',
       'L3_NO2_NO2_column_number_density',
       'L3_NO2_NO2_slant_column_number_density',
       'L3_NO2_absorbing_aerosol_index', 'L3_NO2_cloud_fraction',
       'L3_NO2_sensor_altitude', 'L3_NO2_sensor_azimuth_angle',
       'L3_NO2_sensor_zenith_angle', 'L3_NO2_solar_azimuth_angle',
       'L3_NO2_solar_zenith_angle',
       'L3_NO2_stratospheric_NO2_column_number_density',
       'L3_NO2_tropopause_pressure',
       'L3_NO2_tropospheric_NO2_column_number_density',
       'L3_O3_O3_column_number_density', 'L3_O3_O3_effective_temperature',
       'L3_O3_cloud_fraction', 'L3_O3_sensor_azimuth_angle',
       'L3_O3_sensor_zenith_angle', 'L3_O3_solar_azimuth_angle',
       'L3_O3_solar_zenith_angle', 'L3_CO_CO_column_number_density',
       'L3_CO_H2O_column_number_density', 'L3_CO_cloud_height',
       'L3_CO_sensor_altitude', 'L3_CO_sensor_azimuth_angle',
       'L3_CO_sensor_zenith_angle', 'L3_CO_solar_azimuth_angle',
       'L3_CO_solar_zenith_angle', 'L3_HCHO_HCHO_slant_column_number_density',
       'L3_HCHO_cloud_fraction', 'L3_HCHO_sensor_azimuth_angle',
       'L3_HCHO_sensor_zenith_angle', 'L3_HCHO_solar_azimuth_angle',
       'L3_HCHO_solar_zenith_angle',
       'L3_HCHO_tropospheric_HCHO_column_number_density',
       'L3_HCHO_tropospheric_HCHO_column_number_density_amf',
       'L3_CLOUD_cloud_base_height', 'L3_CLOUD_cloud_base_pressure',
       'L3_CLOUD_cloud_fraction', 'L3_CLOUD_cloud_optical_depth',
       'L3_CLOUD_cloud_top_height', 'L3_CLOUD_cloud_top_pressure',
       'L3_CLOUD_sensor_azimuth_angle', 'L3_CLOUD_sensor_zenith_angle',
       'L3_CLOUD_solar_azimuth_angle', 'L3_CLOUD_solar_zenith_angle',
       'L3_CLOUD_surface_albedo', 'L3_AER_AI_absorbing_aerosol_index',
       'L3_AER_AI_sensor_altitude', 'L3_AER_AI_sensor_azimuth_angle',
       'L3_AER_AI_sensor_zenith_angle', 'L3_AER_AI_solar_azimuth_angle',
       'L3_AER_AI_solar_zenith_angle', 'L3_SO2_SO2_column_number_density',
       'L3_SO2_SO2_column_number_density_amf',
       'L3_SO2_SO2_slant_column_number_density',
       'L3_SO2_absorbing_aerosol_index', 'L3_SO2_cloud_fraction',
       'L3_SO2_sensor_azimuth_angle', 'L3_SO2_sensor_zenith_angle',
       'L3_SO2_solar_azimuth_angle', 'L3_SO2_solar_zenith_angle',
       'L3_CH4_CH4_column_volume_mixing_ratio_dry_air',
       'L3_CH4_aerosol_height', 'L3_CH4_aerosol_optical_depth',
       'L3_CH4_sensor_azimuth_angle', 'L3_CH4_sensor_zenith_angle',
       'L3_CH4_solar_azimuth_angle', 'L3_CH4_solar_zenith_angle'],
      dtype='object')]

In [6]:
coffee_features.head(15)

NameError: name 'coffee_features' is not defined

In [3]:
coffee_quality.head()

,Unnamed: 0,quality_score,view_certificate_1,view_certificate_2,Cupping Protocol and Descriptors,View Green Analysis Details,Request a Sample,Species,Owner,Country of Origin,...,Moisture,Category One Defects,Quakers,Color,Category Two Defects,NA.3,Expiration,Certification Body,Certification Address,Certification Contact
0,0,83.75,NaN,NaN,NaN,NaN,NaN,Robusta,Ankole coffee producers coop,Uganda,...,12 %,0 full defects,0,Green,2 full defects,NaN,"June 26th, 2015",Uganda Coffee Development Authority,"Coffee House, Plot 35, Jinja Road, P.O. Box 72...",Clare Rwakatogoro - 256-41-256940/233073
1,0,83.50,NaN,NaN,NaN,NaN,NaN,Robusta,Nishant Gurjer,India,...,0 %,0 full defects,0,NaN,2 full defects,NaN,"October 31st, 2018",Specialty Coffee Association,"117 W 4th St, Suite 300 Santa Ana, CA 92701",Chris Buck - (562) 624-4100
2,0,83.25,NaN,NaN,NaN,NaN,NaN,Robusta,Andrew Hetzel,India,...,0 %,0 full defects,0,Green,0 full defects,NaN,"April 29th, 2016",Specialty Coffee Association,"117 W 4th St, Suite 300 Santa Ana, CA 92701",Chris Buck - (562) 624-4100
3,0,83.00,NaN,NaN,NaN,NaN,NaN,Robusta,UGACOF,Uganda,...,12 %,0 full defects,0,Green,7 full defects,NaN,"July 14th, 2015",Uganda Coffee Development Authority,"Coffee House, Plot 35, Jinja Road, P.O. Box 72...",Clare Rwakatogoro - 256-41-256940/233073
4,0,83.00,NaN,NaN,NaN,NaN,NaN,Robusta,Katuka Development Trust Ltd,Uganda,...,12 %,0 full defects,0,Green,3 full defects,NaN,"June 26th, 2015",Uganda Coffee Development Authority,"Coffee House, Plot 35, Jinja Road, P.O. Box 72...",Clare Rwakatogoro - 256-41-256940/233073

In [4]:
Y = coffee_quality["quality_score"]

# Data cleaningin and feature engineering

In [5]:
coffee_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 44 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             28 non-null     int64
 1   Species                28 non-null     object
 2   Owner                  28 non-null     object
 3   Country.of.Origin      28 non-null     object
 4   Farm.Name              25 non-null     object
 5   Lot.Number             6 non-null      object
 6   Mill                   20 non-null     object
 7   ICO.Number             17 non-null     object
 8   Company                28 non-null     object
 9   Altitude               25 non-null     object
 10  Region                 26 non-null     object
 11  Producer               26 non-null     object
 12  Number.of.Bags         28 non-null     int64
 13  Bag.Weight             28 non-null     object
 14  In.Country.Partner     28 non-null     object
 15  Harvest.Year           28 non-null     int64
 16  Grading.Date           28 non-null     object
 17  Owner.1                28 non-null     object
 18  Variety                3 non-null      object
 19  Processing.Method      10 non-null     object
 20  Fragrance...Aroma      28 non-null     float64
 21  Flavor                 28 non-null     float64
 22  Aftertaste             28 non-null     float64
 23  Salt...Acid            28 non-null     float64
 24  Bitter...Sweet         28 non-null     float64
 25  Mouthfeel              28 non-null     float64
 26  Uniform.Cup            28 non-null     float64
 27  Clean.Cup              28 non-null     float64
 28  Balance                28 non-null     float64
 29  Cupper.Points          28 non-null     float64
 30  Total.Cup.Points       28 non-null     float64
 31  Moisture               28 non-null     float64
 32  Category.One.Defects   28 non-null     int64
 33  Quakers                28 non-null     int64
 34  Color                  26 non-null     object
 35  Category.Two.Defects   28 non-null     int64
 36  Expiration             28 non-null     object
 37  Certification.Body     28 non-null     object
 38  Certification.Address  28 non-null     object
 39  Certification.Contact  28 non-null     object
 40  unit_of_measurement    28 non-null     object
 41  altitude_low_meters    25 non-null     float64
 42  altitude_high_meters   25 non-null     float64
 43  altitude_mean_meters   25 non-null     float64
dtypes: float64(15), int64(6), object(23)
memory usage: 9.8+ KB

In [6]:
#for this exercise we will only deal with numeric variables

X = coffee_features.select_dtypes(['number'])

## Splitting data for testing

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

In [8]:
#dropping Quakers column and unnamed
#changing one of the altitude to log and droping the original
X_train["altitude_mean_log"] = np.log(X_train["altitude_mean_meters"])
X_train.drop(['altitude_mean_meters'], axis=1, inplace=True)
X_train.drop(['Quakers'], axis=1, inplace=True)
X_train.drop(['Unnamed: 0'], axis=1, inplace=True)

In [9]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22 entries, 17 to 6
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Number.of.Bags        22 non-null     int64
 1   Harvest.Year          22 non-null     int64
 2   Fragrance...Aroma     22 non-null     float64
 3   Flavor                22 non-null     float64
 4   Aftertaste            22 non-null     float64
 5   Salt...Acid           22 non-null     float64
 6   Bitter...Sweet        22 non-null     float64
 7   Mouthfeel             22 non-null     float64
 8   Uniform.Cup           22 non-null     float64
 9   Clean.Cup             22 non-null     float64
 10  Balance               22 non-null     float64
 11  Cupper.Points         22 non-null     float64
 12  Total.Cup.Points      22 non-null     float64
 13  Moisture              22 non-null     float64
 14  Category.One.Defects  22 non-null     int64
 15  Category.Two.Defects  22 non-null     int64
 16  altitude_low_meters   19 non-null     float64
 17  altitude_high_meters  19 non-null     float64
 18  altitude_mean_log     19 non-null     float64
dtypes: float64(15), int64(4)
memory usage: 3.4 KB

In [10]:
altitude_low_meters_mean = X_train["altitude_low_meters"].mean()
altitude_high_meters_mean = X_train["altitude_high_meters"].mean()
altitude_mean_log_mean = X_train["altitude_mean_log"].mean()

In [11]:
# fillna with mean.. 
X_train["altitude_low_meters"] = X_train["altitude_low_meters"].fillna(altitude_low_meters_mean)
X_train["altitude_high_meters"] = X_train["altitude_high_meters"].fillna(altitude_high_meters_mean)
X_train["altitude_mean_log"] = X_train["altitude_mean_log"].fillna(altitude_mean_log_mean)

In [12]:
print(f"altitude low meters mean is {altitude_low_meters_mean}")
print(f"altitude_high_meters_mean is {altitude_high_meters_mean}")
print(f"altitude_mean_log_mean is {altitude_mean_log_mean}")

altitude low meters mean is 1500.3684210526317
altitude_high_meters_mean is 1505.6315789473683
altitude_mean_log_mean is 7.0571530664031155

## Trainining the model

In [13]:
## in order to exemplify how the predict will work.. we will save the y_train
X_test.to_csv("data/X_test.csv")
y_test.to_csv("data/y_test.csv")

In [15]:
#training the model
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)

In [17]:
from sklearn.metrics import mean_squared_error
y_train_pred = reg.predict(X_train)
mse = mean_squared_error(y_train, y_train_pred)
print(mse)

6.701014816713759e-28

In [18]:
#dropping Quakers column and unnamed
#changing one of the altitude to log and droping the original
X_test["altitude_mean_log"] = np.log(X_test["altitude_mean_meters"])
X_test.drop(['altitude_mean_meters'], axis=1, inplace=True)
X_test.drop(['Quakers'], axis=1, inplace=True)
X_test.drop(['Unnamed: 0'], axis=1, inplace=True)
# fillna with mean.. 
X_test["altitude_low_meters"] = X_test["altitude_low_meters"].fillna(altitude_low_meters_mean)
X_test["altitude_high_meters"] = X_test["altitude_high_meters"].fillna(altitude_high_meters_mean)
X_test["altitude_mean_log"] = X_test["altitude_mean_log"].fillna(altitude_mean_log_mean)

In [19]:
y_test_pred = reg.predict(X_test)
mse = mean_squared_error(y_test, y_test_pred)
print(mse)

2.08680004794465e-27